In [22]:
import pandas as pd

# PRE EXPLORATION DATASET

In this jupyter notebook i'm going to take a first observation of the dataset, set them a little and understand what type of informations they contains. <br>
The questions we will analyze in this analysis are: <br>
- Trade openness and employment: Do EU countries with greater trade openness (exports as a share of GDP) show different unemployment levels?
- Trade composition and employment: Is the weight of manufactured goods in a country's trade associated with different unemployment levels?
- Reaction to economic shocks: How did trade and unemployment react to the 2009 and 2020 crises, and which countries recovered fastest?

In [23]:
GDP_FOR_NATION_path= "data/raw_data/gdp_for_nation.csv"
DISOCCUPATION_FOR_NATION_path= "data/raw_data/disoccupation_for_nation.csv"
IN_EX_EU_TRADE_path= "data/raw_data/in_ex_eu_trade.tsv"
IN_EX_EU_TRADE_MANUFACTURED_path= "data/raw_data/in_ex_eu_trade_manufactured.tsv"

In [24]:
GDP_FOR_NATION= pd.read_csv(GDP_FOR_NATION_path)
DISOCCUPATION_FOR_NATION= pd.read_csv(DISOCCUPATION_FOR_NATION_path)
IN_EX_EU_TRADE=  pd.read_csv(IN_EX_EU_TRADE_path, sep="\t")
IN_EX_EU_TRADE_MANUFACTURED= pd.read_csv(IN_EX_EU_TRADE_MANUFACTURED_path, sep= "\t")

In [25]:
GDP_FOR_NATION.head(5)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,na_item,National accounts indicator (ESA 2010),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2016,NaN,10420.1,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2017,NaN,10762.2,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2018,NaN,11157.3,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2019,NaN,11387.4,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2020,NaN,11010.1,NaN,NaN,NaN,NaN,NaN

This dataset "GDP_for_nation" contains informations about the GDP and main components(output, expenditure and income)

In [26]:
GDP_FOR_NATION["STRUCTURE_NAME"].value_counts()

STRUCTURE_NAME
Gross domestic product (GDP) and main components (output, expenditure and income) - annual data    1345
Name: count, dtype: int64

In [27]:
DISOCCUPATION_FOR_NATION.head(5)

,DATAFLOW,LAST UPDATE,freq,age,unit,sex,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2016,6.5,NaN,NaN
1,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2017,5.9,NaN,NaN
2,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2018,5.2,NaN,NaN
3,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2019,4.8,NaN,NaN
4,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2020,6.0,NaN,NaN

This dataset "Disoccupation_for_nation" contains the the unemployment percentage in the labour force

In [28]:
with open(IN_EX_EU_TRADE_path) as f:
    for _ in range(3):
        print(repr(f.readline()))

'freq,indic_et,sitc06,partner,geo\\TIME_PERIOD\t2002 \t2003 \t2004 \t2005 \t2006 \t2007 \t2008 \t2009 \t2010 \t2011 \t2012 \t2013 \t2014 \t2015 \t2016 \t2017 \t2018 \t2019 \t2020 \t2021 \t2022 \t2023 \t2024 \t2025 \n'
'A,CONT_EXP_EU,SITC0_1,EU27_2020,AT\t2.6 \t2.8 \t2.9 \t2.9 \t3.0 \t3.0 \t3.1 \t3.0 \t2.9 \t2.9 \t2.9 \t2.8 \t2.9 \t2.8 \t2.8 \t2.8 \t2.8 \t2.9 \t2.9 \t2.9 \t2.9 \t3.0 \t2.9 \t2.8 \n'
'A,CONT_EXP_EU,SITC0_1,EU27_2020,BE\t11.5 \t11.3 \t11.1 \t10.8 \t10.4 \t10.2 \t10.1 \t10.3 \t9.8 \t9.8 \t9.9 \t9.5 \t9.5 \t9.7 \t9.8 \t9.7 \t9.4 \t9.4 \t9.4 \t9.1 \t8.9 \t9.0 \t9.1 \t9.1 \n'

In [29]:
IN_EX_EU_TRADE.head(5)

,"freq,indic_et,sitc06,partner,geo\TIME_PERIOD",2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,"A,CONT_EXP_EU,SITC0_1,EU27_2020,AT",2.6,2.8,2.9,2.9,3.0,3.0,3.1,3.0,2.9,...,2.8,2.8,2.8,2.9,2.9,2.9,2.9,3.0,2.9,2.8
1,"A,CONT_EXP_EU,SITC0_1,EU27_2020,BE",11.5,11.3,11.1,10.8,10.4,10.2,10.1,10.3,9.8,...,9.8,9.7,9.4,9.4,9.4,9.1,8.9,9.0,9.1,9.1
2,"A,CONT_EXP_EU,SITC0_1,EU27_2020,BG",0.3,0.2,0.3,0.3,0.3,0.3,0.4,0.6,0.7,...,0.7,0.8,0.8,0.8,0.8,0.8,0.8,0.7,0.6,0.6
3,"A,CONT_EXP_EU,SITC0_1,EU27_2020,CY",0.0,0.1,0.1,0.1,0.0,0.1,0.0,0.0,0.0,...,0.0,0.0,0.1,0.1,0.1,0.1,0.1,0.0,0.1,0.1
4,"A,CONT_EXP_EU,SITC0_1,EU27_2020,CZ",0.8,0.8,1.0,1.3,1.4,1.5,1.7,1.6,1.6,...,2.1,2.0,2.0,2.0,2.1,2.1,2.2,2.4,2.4,2.4

In [30]:

IN_EX_EU_TRADE_indicator= IN_EX_EU_TRADE[IN_EX_EU_TRADE.columns[0]].str.split(",", expand=True)

In [31]:
IN_EX_EU_TRADE_indicator.head(2)

   0            1        2          3   4
0  A  CONT_EXP_EU  SITC0_1  EU27_2020  AT
1  A  CONT_EXP_EU  SITC0_1  EU27_2020  BE

In [32]:
IN_EX_EU_TRADE_indicator.rename(columns={
    0: "freq",
    1: "indic_et",
    2: "sitc06",
    3: "partner",
    4: "geo"
}, inplace= True)

In [33]:
IN_EX_EU_TRADE_nocol0= IN_EX_EU_TRADE.drop(["freq,indic_et,sitc06,partner,geo\TIME_PERIOD"], axis=1)

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\Matteo_Papucci\AppData\Local\Temp\ipykernel_44928\1421162165.py:1: SyntaxWarning: invalid escape sequence '\T'
  IN_EX_EU_TRADE_nocol0= IN_EX_EU_TRADE.drop(["freq,indic_et,sitc06,partner,geo\TIME_PERIOD"], axis=1)

In [34]:
IN_EX_EU_TRADE_nocol0.head(1)

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,2.6,2.8,2.9,2.9,3.0,3.0,3.1,3.0,2.9,2.9,...,2.8,2.8,2.8,2.9,2.9,2.9,2.9,3.0,2.9,2.8

In [35]:
IN_EX_EU_TRADE=pd.concat([IN_EX_EU_TRADE_indicator,IN_EX_EU_TRADE_nocol0], join= "outer", axis=1)

In [36]:
IN_EX_EU_TRADE.head(2)

,freq,indic_et,sitc06,partner,geo,2002,2003,2004,2005,2006,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,A,CONT_EXP_EU,SITC0_1,EU27_2020,AT,2.6,2.8,2.9,2.9,3.0,...,2.8,2.8,2.8,2.9,2.9,2.9,2.9,3.0,2.9,2.8
1,A,CONT_EXP_EU,SITC0_1,EU27_2020,BE,11.5,11.3,11.1,10.8,10.4,...,9.8,9.7,9.4,9.4,9.4,9.1,8.9,9.0,9.1,9.1

In [37]:
IN_EX_EU_TRADE_melted=IN_EX_EU_TRADE.melt(
    id_vars= ["freq", "indic_et", "sitc06", "partner", "geo"],
    var_name= "time_period",
    value_name= "OBS_VALUE"
)

In [38]:
IN_EX_EU_TRADE_melted.head(5)

  freq     indic_et   sitc06    partner geo time_period  OBS_VALUE
0    A  CONT_EXP_EU  SITC0_1  EU27_2020  AT       2002         2.6
1    A  CONT_EXP_EU  SITC0_1  EU27_2020  BE       2002        11.5
2    A  CONT_EXP_EU  SITC0_1  EU27_2020  BG       2002         0.3
3    A  CONT_EXP_EU  SITC0_1  EU27_2020  CY       2002         0.0
4    A  CONT_EXP_EU  SITC0_1  EU27_2020  CZ       2002         0.8

In [39]:
IN_EX_EU_TRADE_melted[
    (IN_EX_EU_TRADE_melted["sitc06"] == "SITC0_1") & (IN_EX_EU_TRADE_melted["geo"] == "AT")
]

       freq     indic_et   sitc06        partner geo time_period  OBS_VALUE
0         A  CONT_EXP_EU  SITC0_1      EU27_2020  AT       2002         2.6
28        A  CONT_EXP_EU  SITC0_1  EXT_EU27_2020  AT       2002         1.3
448       A  CONT_IMP_EU  SITC0_1      EU27_2020  AT       2002         3.3
476       A  CONT_IMP_EU  SITC0_1  EXT_EU27_2020  AT       2002         1.1
896       A  MIO_BAL_VAL  SITC0_1      EU27_2020  AT       2002      -728.5
...     ...          ...      ...            ...  ..         ...        ...
121184    A  PC_IMP_PROD  SITC0_1          WORLD  AT       2025         9.1
121792    A   PC_TOT_EXP  SITC0_1      EU27_2020  AT       2025        81.2
121820    A   PC_TOT_EXP  SITC0_1  EXT_EU27_2020  AT       2025        18.8
122240    A   PC_TOT_IMP  SITC0_1      EU27_2020  AT       2025        89.1
122268    A   PC_TOT_IMP  SITC0_1  EXT_EU27_2020  AT       2025        10.9

[552 rows x 7 columns]

In [40]:
IN_EX_EU_TRADE_melted["indic_et"].value_counts()

indic_et
MIO_BAL_VAL    15936
MIO_EXP_VAL    15936
MIO_IMP_VAL    15936
PC_EXP_PROD    15936
PC_IMP_PROD    15936
CONT_EXP_EU    10752
CONT_IMP_EU    10752
PC_TOT_EXP     10752
PC_TOT_IMP     10752
Name: count, dtype: int64

This DS "IN_EX_EU_TRADE_melted contains: <br>
- MIO_EXP_VAL: exports in millions of euros
- MIO_IMP_VAL: imports in millions of euros
- MIO_BAL_VAL:difference between exports and imports

- PC_EXP_PROD: how much a product's category weighs on the total exports percentage
- PC_IMP_PROD:how much a product's category weighs on the total  imports percentage

- CONT_EXP_EU: share of exports to the EU
- CONT_IMP_EU: share of imports from EU

- PC_TOT_EXP: share of total exports in %
- PC_TOT_IMP: share of total imports in %

In [41]:
IN_EX_EU_TRADE_melted.to_csv("data/semi-processed_data/IN_EX_EU_TRADE_melted.csv", index= False)

In [42]:
IN_EX_EU_TRADE_MANUFACTURED_indicator=IN_EX_EU_TRADE_MANUFACTURED[IN_EX_EU_TRADE_MANUFACTURED.columns[0]].str.split(",", expand=True)

In [43]:
IN_EX_EU_TRADE_MANUFACTURED_indicator.head(3)

   0            1        2    3          4
0  A  MIO_BAL_VAL  SITC6_8  ACP  EU27_2020
1  A  MIO_BAL_VAL  SITC6_8   AD  EU27_2020
2  A  MIO_BAL_VAL  SITC6_8   AE  EU27_2020

In [44]:
IN_EX_EU_TRADE_MANUFACTURED_indicator[2].value_counts()

2
SITC6_8    1160
Name: count, dtype: int64

In [45]:
IN_EX_EU_TRADE_MANUFACTURED_indicator.rename(columns={
    0: "freq",
    1: "indic_et",
    2: "sitc6_8",
    3: "partner",
    4: "geo"
}, inplace= True)

In [46]:
IN_EX_EU_TRADE_MANUFACTURED_indicator.head(3)

  freq     indic_et  sitc6_8 partner        geo
0    A  MIO_BAL_VAL  SITC6_8     ACP  EU27_2020
1    A  MIO_BAL_VAL  SITC6_8      AD  EU27_2020
2    A  MIO_BAL_VAL  SITC6_8      AE  EU27_2020

In [47]:
IN_EX_EU_TRADE_MANUFACTURED_nocol0= IN_EX_EU_TRADE_MANUFACTURED.drop(["freq,indic_et,sitc06,partner,geo\TIME_PERIOD"], axis=1)

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\Matteo_Papucci\AppData\Local\Temp\ipykernel_44928\1873711501.py:1: SyntaxWarning: invalid escape sequence '\T'
  IN_EX_EU_TRADE_MANUFACTURED_nocol0= IN_EX_EU_TRADE_MANUFACTURED.drop(["freq,indic_et,sitc06,partner,geo\TIME_PERIOD"], axis=1)

In [48]:
IN_EX_EU_TRADE_MANUFACTURED= pd.concat([IN_EX_EU_TRADE_MANUFACTURED_indicator, IN_EX_EU_TRADE_MANUFACTURED_nocol0], join="outer", axis=1)

In [49]:
IN_EX_EU_TRADE_MANUFACTURED.head(3)

,freq,indic_et,sitc6_8,partner,geo,2002,2003,2004,2005,2006,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,A,MIO_BAL_VAL,SITC6_8,ACP,EU27_2020,547.1,1517.6,1464.1,1511.6,1488.5,...,1159.5,1699.0,1311.3,2098.8,1829.7,2026.0,-94.8,2073.1,1332.4,-174.1
1,A,MIO_BAL_VAL,SITC6_8,AD,EU27_2020,397.6,408.3,395.7,399.0,412.8,...,339.0,338.7,346.5,328.9,524.8,313.3,433.9,442.1,427.2,462.7
2,A,MIO_BAL_VAL,SITC6_8,AE,EU27_2020,2781.1,2378.8,2398.2,2996.2,3467.9,...,6377.8,6212.9,5232.4,5847.5,5037.3,5684.0,6045.8,7942.1,10136.3,10744.9

In [50]:
IN_EX_EU_TRADE_MANUFACTURED_melted=IN_EX_EU_TRADE_MANUFACTURED.melt(
    id_vars= ["freq", "indic_et", "sitc6_8", "partner", "geo"],
    var_name= "time_period",
    value_name= "OBS_VALUE"
)

In [51]:
IN_EX_EU_TRADE_MANUFACTURED_melted.head(3)

  freq     indic_et  sitc6_8 partner        geo time_period OBS_VALUE
0    A  MIO_BAL_VAL  SITC6_8     ACP  EU27_2020       2002     547.1
1    A  MIO_BAL_VAL  SITC6_8      AD  EU27_2020       2002     397.6
2    A  MIO_BAL_VAL  SITC6_8      AE  EU27_2020       2002    2781.1

In [52]:
IN_EX_EU_TRADE_MANUFACTURED_melted["indic_et"].value_counts()

indic_et
MIO_BAL_VAL    5568
MIO_EXP_VAL    5568
MIO_IMP_VAL    5568
PC_EXP_PART    5568
PC_IMP_PART    5568
Name: count, dtype: int64

This DS "IN_EX_EU_TRADE_melted contains specific data for Manufactured goods (SITC6_8): <br>
- MIO_BAL_VAL: difference between exports and imports
- MIO_EXP_VAL: exports in millions of euros 
- MIO_IMP_VAL:imports in millions of euros

- PC_EXP_PART: how much a product's category weighs on the total exports percentage
- PC_IMP_PART:how much a product's category weighs on the total  imports percentage

In [53]:
IN_EX_EU_TRADE_MANUFACTURED_melted.head(3)

  freq     indic_et  sitc6_8 partner        geo time_period OBS_VALUE
0    A  MIO_BAL_VAL  SITC6_8     ACP  EU27_2020       2002     547.1
1    A  MIO_BAL_VAL  SITC6_8      AD  EU27_2020       2002     397.6
2    A  MIO_BAL_VAL  SITC6_8      AE  EU27_2020       2002    2781.1

In [54]:
IN_EX_EU_TRADE_MANUFACTURED_melted.to_csv("data/semi-processed_data/IN_EX_EU_TRADE_MANUFACTURED_melted.csv", index= False)

At first glance, the `IN_EX_EU_TRADE_MANUFACTURED_melted` DataFrame will not be useful for the analysis being conducted in this project. <br>
It relates to general European import/export data, whereas my goal is to analyze individual countries.

In [55]:
IN_EX_EU_TRADE_MANUFACTURED_melted["geo"].value_counts()

geo
EU27_2020    27840
Name: count, dtype: int64


The `value_counts()` method confirms that the dataframe contains data only for Europe in general, so we will not use it in our analyses.