#  INPORT/EXPORT DIAGNOSTIC EXPLORATION
In this notebook I am proceeding to conduct a diagnostic analysis of Inport/Export dataset and preparing it for next analysis.

In [75]:
import pandas as pd
from pathlib import Path

In [76]:
INPORT_EXPORT_path= Path.cwd().parent/"data/semi-processed_data/IN_EX_EU_TRADE_melted.csv"

In [77]:
INPORT_EXPORT_EU= pd.read_csv(INPORT_EXPORT_path)

In [78]:
## Third Dataset: INPORT_EXPORT_EU

In [79]:
INPORT_EXPORT_EU.head(5)

  freq     indic_et   sitc06    partner geo  time_period  OBS_VALUE
0    A  CONT_EXP_EU  SITC0_1  EU27_2020  AT         2002        2.6
1    A  CONT_EXP_EU  SITC0_1  EU27_2020  BE         2002       11.5
2    A  CONT_EXP_EU  SITC0_1  EU27_2020  BG         2002        0.3
3    A  CONT_EXP_EU  SITC0_1  EU27_2020  CY         2002        0.0
4    A  CONT_EXP_EU  SITC0_1  EU27_2020  CZ         2002        0.8

In [80]:
INPORT_EXPORT_EU.info()

<class 'pandas.DataFrame'>
RangeIndex: 122688 entries, 0 to 122687
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   freq         122688 non-null  str
 1   indic_et     122688 non-null  str
 2   sitc06       122688 non-null  str
 3   partner      122688 non-null  str
 4   geo          122688 non-null  str
 5   time_period  122688 non-null  int64
 6   OBS_VALUE    122688 non-null  float64
dtypes: float64(1), int64(1), str(5)
memory usage: 6.6 MB

In [81]:
INPORT_EXPORT_EU.shape

(122688, 7)

In [82]:
INPORT_EXPORT_EU.isna().sum()

freq           0
indic_et       0
sitc06         0
partner        0
geo            0
time_period    0
OBS_VALUE      0
dtype: int64

In [83]:
INPORT_EXPORT_EU.nunique()

freq               1
indic_et           9
sitc06             8
partner            3
geo               28
time_period       24
OBS_VALUE      40296
dtype: int64

In [84]:
INPORT_EXPORT_EU["indic_et"].value_counts()

indic_et
MIO_BAL_VAL    15936
MIO_EXP_VAL    15936
MIO_IMP_VAL    15936
PC_EXP_PROD    15936
PC_IMP_PROD    15936
CONT_EXP_EU    10752
CONT_IMP_EU    10752
PC_TOT_EXP     10752
PC_TOT_IMP     10752
Name: count, dtype: int64

In [85]:
INPORT_EXPORT_EU["sitc06"].value_counts()

sitc06
SITC0_1    15336
SITC2_4    15336
SITC3      15336
SITC5      15336
SITC6_8    15336
SITC7      15336
SITC9      15336
TOTAL      15336
Name: count, dtype: int64

In [86]:
INPORT_EXPORT_EU["partner"].value_counts()

partner
EU27_2020        48384
EXT_EU27_2020    48384
WORLD            25920
Name: count, dtype: int64

In [87]:
INPORT_EXPORT_EU["geo"].value_counts()

geo
AT           4416
BE           4416
BG           4416
CY           4416
CZ           4416
DE           4416
DK           4416
EE           4416
EL           4416
ES           4416
FI           4416
FR           4416
HR           4416
HU           4416
IE           4416
IT           4416
LT           4416
LU           4416
LV           4416
MT           4416
NL           4416
PL           4416
PT           4416
RO           4416
SE           4416
SI           4416
SK           4416
EU27_2020    3456
Name: count, dtype: int64

After this quick look to the dataset, i control if "WORLD" of the column "partner" have all the product categories.<br>
The plan is to filter the "partner" only with the word market, and create due different dataset: one with allo the product categories and another with the total.<br>
The "indic_et" column will be filter by:
- MIO_BAL_VAL: difference between exports and imports
- MIO_EXP_VAL: exports in millions of euros 
- MIO_IMP_VAL:imports in millions of euros

In [88]:
INPORT_EXPORT_EU[INPORT_EXPORT_EU["partner"] == "WORLD"]["sitc06"].value_counts()

sitc06
SITC0_1    3240
SITC2_4    3240
SITC3      3240
SITC5      3240
SITC6_8    3240
SITC7      3240
SITC9      3240
TOTAL      3240
Name: count, dtype: int64

The "WORD" in "partner"'s column contain all the product categories, so i can continue with my original plan. <br>
i will also drop the freq column that's not usefull.

In [89]:
in_ex_EU_world= INPORT_EXPORT_EU[INPORT_EXPORT_EU["partner"] == "WORLD"].drop(["freq"], axis=1)

In [90]:
in_ex_EU_world["partner"].value_counts()

partner
WORLD    25920
Name: count, dtype: int64

The "partner"'s column is not necessary anymore, i drop pt.

In [91]:
in_ex_EU_world["geo"].value_counts()

geo
AT    960
BE    960
BG    960
CY    960
CZ    960
DE    960
DK    960
EE    960
EL    960
ES    960
FI    960
FR    960
HR    960
HU    960
IE    960
IT    960
LT    960
LU    960
LV    960
MT    960
NL    960
PL    960
PT    960
RO    960
SE    960
SI    960
SK    960
Name: count, dtype: int64

Filtering the dataframe by the "WORD" parameter removed the "EU27_2020" item. Should I need it, I can obtain it by summing the individual countries.

In [92]:
in_ex_EU_world=in_ex_EU_world.drop(["partner"], axis=1)

In [93]:
in_ex_EU_world.head(5)

        indic_et   sitc06 geo  time_period  OBS_VALUE
952  MIO_BAL_VAL  SITC0_1  AT         2002     -504.7
953  MIO_BAL_VAL  SITC0_1  BE         2002     2625.4
954  MIO_BAL_VAL  SITC0_1  BG         2002      210.9
955  MIO_BAL_VAL  SITC0_1  CY         2002     -302.5
956  MIO_BAL_VAL  SITC0_1  CZ         2002     -688.3

In [94]:
in_ex_EU_world.shape

(25920, 5)

In [95]:
#filter the indic_et
list_indic= ["MIO_BAL_VAL","MIO_EXP_VAL", "MIO_IMP_VAL"]
in_ex_EU_world=in_ex_EU_world[ in_ex_EU_world["indic_et"].isin(list_indic)]

In [96]:
in_ex_EU_world["indic_et"].value_counts()

indic_et
MIO_BAL_VAL    5184
MIO_EXP_VAL    5184
MIO_IMP_VAL    5184
Name: count, dtype: int64

I will explain more clearly the "indic_et" values and the "sitc06" values, before proceding with the creation of the diffent df. <br>
 I will rename the firsts and create a a product-clarification column for the seconds.product_code
 I also rename the columns to be consistent with the previous dataframes. <br>
 i will not create a "country" column, because i will use these dataframe principally for join.

In [97]:
in_ex_EU_world["indic_et"]= in_ex_EU_world["indic_et"].replace({"MIO_BAL_VAL": "balance", "MIO_EXP_VAL": "export", "MIO_IMP_VAL": "import"})

In [98]:
in_ex_EU_world["indic_et"].value_counts()

indic_et
balance    5184
export     5184
import     5184
Name: count, dtype: int64

In [99]:
product_labels = {
    "SITC0_1": "food_drinks_tobacco",
    "SITC2_4": "raw_materials",
    "SITC3": "mineral_fuels",
    "SITC5": "chemicals",
    "SITC6_8": "other_manufactured",
    "SITC7": "machinery_transport",
    "SITC9": "unclassified",
    "TOTAL": "total"
}
in_ex_EU_world["product_description"] = in_ex_EU_world["sitc06"].map(product_labels)

In [100]:
in_ex_EU_world["product_description"].value_counts()

product_description
food_drinks_tobacco    1944
raw_materials          1944
mineral_fuels          1944
chemicals              1944
other_manufactured     1944
machinery_transport    1944
unclassified           1944
total                  1944
Name: count, dtype: int64

In [101]:
in_ex_EU_world= in_ex_EU_world.rename(columns={"sitc06":"product_code", "geo": "country_code", "time_period": "year" , "OBS_VALUE": "value_meur"})

In [102]:
#change the order of the columns:as
col_order = ["country_code","product_code", "product_description", "year", "indic_et", "value_meur"]
in_ex_EU_world=in_ex_EU_world[col_order]

Now i create two diffents dataset: one for product categories and one for total.

In [103]:
product_list= ["SITC0_1","SITC2_4","SITC3","SITC5","SITC6_8","SITC7", "SITC9"]
in_ex_EU_prcategories= in_ex_EU_world[in_ex_EU_world["product_code"].isin(product_list)].copy()
in_ex_EU_total= in_ex_EU_world[in_ex_EU_world["product_code"] =="TOTAL"].copy()

In [104]:
in_ex_EU_prcategories["product_code"].value_counts()

product_code
SITC0_1    1944
SITC2_4    1944
SITC3      1944
SITC5      1944
SITC6_8    1944
SITC7      1944
SITC9      1944
Name: count, dtype: int64

In [105]:
in_ex_EU_prcategories.head(5)

    country_code product_code  product_description  year indic_et  value_meur
952           AT      SITC0_1  food_drinks_tobacco  2002  balance      -504.7
953           BE      SITC0_1  food_drinks_tobacco  2002  balance      2625.4
954           BG      SITC0_1  food_drinks_tobacco  2002  balance       210.9
955           CY      SITC0_1  food_drinks_tobacco  2002  balance      -302.5
956           CZ      SITC0_1  food_drinks_tobacco  2002  balance      -688.3

In [106]:
in_ex_EU_total["product_code"].value_counts()

product_code
TOTAL    1944
Name: count, dtype: int64

Now i will save the two df in the clean_data folder

In [107]:
in_ex_EU_total.head(5)

     country_code product_code product_description  year indic_et  value_meur
1533           AT        TOTAL               total  2002  balance       395.4
1534           BE        TOTAL               total  2002  balance     18841.3
1535           BG        TOTAL               total  2002  balance     -2348.4
1536           CY        TOTAL               total  2002  balance     -3453.5
1537           CZ        TOTAL               total  2002  balance     -2289.0

In [108]:
in_ex_EU_total["country_code"].nunique()

27

In [109]:
in_ex_EU_prcategories["country_code"].nunique()

27

In [110]:
in_ex_EU_prcategories.to_csv(Path.cwd().parent/"data/clean_data/in_ex_EU_prcategories.csv", index= False)
in_ex_EU_total.to_csv(Path.cwd().parent/"data/clean_data/in_ex_EU_total.csv", index= False)

I create the database and save the cleaned DataFrame inside it.

In [111]:
import sqlite3
conn = sqlite3.connect(Path.cwd().parent/"database/ue_market.db")

In [112]:
in_ex_EU_prcategories.to_sql("trade_category", conn, if_exists="replace", index=False)
in_ex_EU_total.to_sql("trade_total", conn, if_exists="replace", index=False)

1944